name: Merge branch to uat
on:
  push:
    branches:
      - '*'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge staging -> uat
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: uat
          github_token: ${{ github.ACCESS_TOKEN }}
